spring:
  application:
    name: ACCOUNTING-SERVICE
  kafka:
    consumer:
      group-id: accounting-service-group

logging:
  level:
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR