server:
  port: 8888

spring:
  application:
    name: API-GATEWAY
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.javaguru.by/realms/v.dubov
  cloud:
    gateway:
      routes:
        - id: education-service
          uri: lb://EDUCATION-SERVICE
          predicates:
            - Path=/api/v1/education/**
          filters:
            - AuthenticationFilter

        - id: resources-service
          uri: lb://RESOURCES-SERVICE
          predicates:
            - Path=/api/v1/resources/**
          filters:
            - AuthenticationFilter

        - id: accounting-service
          uri: lb://ACCOUNTING-SERVICE
          predicates:
            - Path=/api/v1/accounting/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthenticationFilter
