server:
  port: 8888

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: education-service
          uri: lb://EDUCATION-SERVICE
          predicates:
            - Path=/api/v1/education/**
          filters:
            - AuthenticationFilter

        - id: resources-service
          uri: lb://RESOURCES-SERVICE
          predicates:
            - Path=/api/v1/resources/**
          filters:
            - AuthenticationFilter

        - id: accounting-service
          uri: lb://ACCOUNTING-SERVICE
          predicates:
            - Path=/api/v1/accounting/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthenticationFilter

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,refresh,busrefresh,gateway

app:
  jwt:
    secret: ${JWT_SECRET}

clients:
  identity-service:
    url: "http://IDENTITY-SERVICE/api/auth/validate"
