server:
  port: 0

spring:
  main:
    banner-mode: console
  cloud:
    discovery:
      enabled: true

springdoc:
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: mapping,health,retryevents,circuitbreakerevents,env,refresh
  endpoint:
    env:
      show-values: always
      keys-to-sanitize: []
    health:
      show-details: always
      keys-to-sanitize: []

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-URL
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
