spring:
  application:
    name: EDUCATION-SERVICE
  datasource:
    url: ${EDUCATION_DATABASE_URL:jdbc:postgresql://localhost:18081/education-db}
    username: ${EDUCATION_DATABASE_USERNAME:admin}
    password: ${EDUCATION_DATABASE_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
