spring:
  application:
    name: EDUCATION-SERVICE
  datasource:
    url: ${EDUCATION_DATABASE_URL:jdbc:postgresql://localhost:18081/education-db}
    username: ${EDUCATION_DATABASE_USERNAME:admin}
    password: ${EDUCATION_DATABASE_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-URL
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 5
        sliding-window-type: count_based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        event-consumer-buffer-size: 10
        register-health-indicator: true #adds statistics to Actuator's app endpoints
        permitted-number-of-calls-in-half-open-state: 3

    instances:
      accounting-service:
        base-config: default
      resources-service:
        base-config: default

  retry:
    retry-aspect-order: 2
    configs:
      default:
        max-attempts: 10
        wait-duration: 5s
    instances:
      accounting-service:
        base-config: default
      resources-service:
        base-config: default