spring:
  application:
    name: EDUCATION-SERVICE
  datasource:
    url: ${EDUCATION_DATABASE_URL:jdbc:postgresql://localhost:18081/education-db}
    username: ${EDUCATION_DATABASE_USERNAME:admin}
    password: ${EDUCATION_DATABASE_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: default

  kafka:
    consumer:
      group-id: education-service-group

kafka:
  transaction:
    accounting: allocate-budget-tx-${random.value}
    resource: resource-check-tx-${random.value}
    notify: notify-tx-${random.value}

outbox:
  scheduler:
    batch-size: 3
    interval-ms: 5000

springdoc:
  show-actuator: true

logging:
  level:
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR