spring:
  application:
    name: IDENTITY-SERVICE
  datasource:
    url: ${IDENTITY_DATABASE_URL:jdbc:postgresql://localhost:18091/identity-db}
    username: ${IDENTITY_DATABASE_USERNAME:admin}
    password: ${IDENTITY_DATABASE_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: default

security:
  jwt:
    secret: ${JWT_SECRET}
    lifetimeMs: 1800000
