spring:
  application:
    name: NOTIFICATION-SERVICE
  kafka:
    consumer:
      group-id: notification-service-group

logging:
  level:
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR