spring:
  application:
    name: RESOURCES-SERVICE
  kafka:
    consumer:
      group-id: resources-service-group

logging:
  level:
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR